export enum CodeTypes {
  MODULE_CALL,
  MODULE_CALL_GLOBAL,
  MODULE_CALL_LOCAL,
  FUNCTION,
  PACKAGE_INSTANCE,
  CLASS_CONSTRUCTOR,
  CLASS_OR_MODULE_PROPERTY,
  LOCAL_VARIABLE,
  CUSTOM_OBJECT,
  DEFINITION,
  IMPORT
}
